CARDS = [
    # =========================================================================
    # PHASE 1 — Economy & Mild Buffs (15 cards, common/uncommon)
    # =========================================================================
    {
        "id": "pocket_change",
        "name": "Pocket Change",
        "desc": "You rummage through the battlefield and find some loose coins.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 0,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 10}],
    },
    {
        "id": "war_tax",
        "name": "War Tax",
        "desc": "The king levies a tax on both sides to fund the ongoing absurdity.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "both", "amount": 5}],
    },
    {
        "id": "pawn_stimulus",
        "name": "Pawn Stimulus Package",
        "desc": "The treasury sends a bailout check to every pawn on your side.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.8,
        "cooldown": 0,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 15}],
    },
    {
        "id": "street_hustle",
        "name": "Street Hustle",
        "desc": "Your bishop runs a three-card monte scheme between moves.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 0,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 8}],
    },
    {
        "id": "lucky_penny",
        "name": "Lucky Penny",
        "desc": "A pawn trips over a coin and gains unearned confidence.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 0,
        "tags": ["economy", "buff"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 5},
            {"type": "chaos", "player": "self", "amount": 3},
        ],
    },
    {
        "id": "minor_ward",
        "name": "Minor Ward",
        "desc": "A faint magical shimmer protects one of your pieces from harm.",
        "rarity": "uncommon",
        "phase": 1,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["buff", "defense"],
        "effects": [{"type": "shield", "target": "random_self", "duration": 2}],
    },
    {
        "id": "pawn_pep_talk",
        "name": "Pawn Pep Talk",
        "desc": "Your king gives an inspiring speech and the pawns feel slightly less expendable.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["buff", "chaos"],
        "effects": [{"type": "chaos", "player": "self", "amount": 5}],
    },
    {
        "id": "toll_bridge",
        "name": "Toll Bridge",
        "desc": "You erect a toll booth on a diagonal — the enemy bishop is furious.",
        "rarity": "uncommon",
        "phase": 1,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["economy", "debuff"],
        "effects": [{"type": "gold", "player": "self", "amount": 12}],
    },
    {
        "id": "foragers_luck",
        "name": "Forager's Luck",
        "desc": "Your knights discover a mushroom patch in no-man's-land.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.8,
        "cooldown": 0,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 7}],
    },
    {
        "id": "chaotic_vibes",
        "name": "Chaotic Vibes",
        "desc": "Everyone on the board feels a strange tingle — chaos energy surges.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["chaos"],
        "effects": [{"type": "chaos", "player": "both", "amount": 5}],
    },
    {
        "id": "cold_shoulder",
        "name": "Cold Shoulder",
        "desc": "An icy draft from the north briefly slows an enemy piece.",
        "rarity": "uncommon",
        "phase": 1,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["debuff"],
        "effects": [{"type": "freeze", "target": "random_enemy", "duration": 1}],
    },
    {
        "id": "spare_parts",
        "name": "Spare Parts",
        "desc": "You scavenge materials from the rubble and cobble together some gold.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.8,
        "cooldown": 0,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 6}],
    },
    {
        "id": "iron_resolve",
        "name": "Iron Resolve",
        "desc": "One of your pieces stiffens with determination and refuses to die.",
        "rarity": "uncommon",
        "phase": 1,
        "weight": 1.8,
        "cooldown": 3,
        "tags": ["buff", "defense"],
        "effects": [{"type": "shield", "target": "random_self", "duration": 3}],
    },
    {
        "id": "bribe_the_ref",
        "name": "Bribe the Ref",
        "desc": "You slip the arbiter a few coins — suddenly the rules feel more flexible.",
        "rarity": "uncommon",
        "phase": 1,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "gold", "player": "self", "amount": -5},
            {"type": "chaos", "player": "self", "amount": 8},
        ],
    },
    {
        "id": "warm_up_round",
        "name": "Warm-Up Round",
        "desc": "Both sides limber up — a card is drawn from the chaos deck.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.2,
        "cooldown": 2,
        "tags": ["chaos"],
        "effects": [{"type": "draw_cards", "count": 1}],
    },

    # =========================================================================
    # PHASE 2 — Mixed Economy, Buffs, Light Attacks (25 cards)
    # =========================================================================
    {
        "id": "stray_cannonball",
        "name": "Stray Cannonball",
        "desc": "A cannonball from a distant war crashes into a random enemy piece.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["damage"],
        "effects": [{"type": "destroy", "target": "random_enemy"}],
    },
    {
        "id": "pickpocket_pawn",
        "name": "Pickpocket Pawn",
        "desc": "A sneaky pawn lifts some gold from the opponent's coffers.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["economy"],
        "effects": [{"type": "steal_gold", "amount": 10}],
    },
    {
        "id": "knights_gambit_casino",
        "name": "Knight's Gambit Casino",
        "desc": "Your knight opens an illegal gambling den mid-game — profits roll in.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 20}],
    },
    {
        "id": "frostbite",
        "name": "Frostbite",
        "desc": "A bitter cold snap freezes an enemy piece solid for two turns.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 3,
        "tags": ["debuff"],
        "effects": [{"type": "freeze", "target": "random_enemy", "duration": 2}],
    },
    {
        "id": "conscript_recruit",
        "name": "Conscript Recruit",
        "desc": "A bewildered peasant is shoved onto the board with a helmet and a prayer.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.2,
        "cooldown": 2,
        "tags": ["summon"],
        "effects": [{"type": "spawn", "piece": "p", "square": "random_empty"}],
    },
    {
        "id": "energy_siphon",
        "name": "Energy Siphon",
        "desc": "Dark tendrils drain chaos energy from your opponent and funnel it to you.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 2,
        "tags": ["chaos", "debuff"],
        "effects": [
            {"type": "chaos", "player": "opponent", "amount": -5},
            {"type": "chaos", "player": "self", "amount": 5},
        ],
    },
    {
        "id": "goblin_ambush",
        "name": "Goblin Ambush",
        "desc": "Goblins leap from the board edges and shank a random piece.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["damage"],
        "effects": [{"type": "destroy", "target": "random_any"}],
    },
    {
        "id": "wormhole_transit",
        "name": "Wormhole Transit",
        "desc": "A miniature wormhole opens and relocates an enemy piece somewhere inconvenient.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 2,
        "tags": ["movement", "chaos"],
        "effects": [{"type": "teleport", "target": "random_enemy"}],
    },
    {
        "id": "double_agent",
        "name": "Double Agent",
        "desc": "One of the opponent's pieces has been working for you all along — gold is transferred.",
        "rarity": "rare",
        "phase": 2,
        "weight": 1.2,
        "cooldown": 4,
        "tags": ["economy"],
        "effects": [{"type": "steal_gold", "amount": 20}],
    },
    {
        "id": "banana_peel",
        "name": "Banana Peel",
        "desc": "Someone left a banana peel on the board — an enemy piece slips to a random square.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["movement", "chaos"],
        "effects": [{"type": "teleport", "target": "random_enemy"}],
    },
    {
        "id": "smugglers_crate",
        "name": "Smuggler's Crate",
        "desc": "A mysterious crate washes ashore containing gold and a sense of unease.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 15},
            {"type": "chaos", "player": "self", "amount": 3},
        ],
    },
    {
        "id": "shield_wall",
        "name": "Shield Wall",
        "desc": "Your front line locks shields — one piece becomes temporarily invulnerable.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 3,
        "tags": ["defense", "buff"],
        "effects": [{"type": "shield", "target": "random_self", "duration": 3}],
    },
    {
        "id": "tavern_brawl",
        "name": "Tavern Brawl",
        "desc": "A fight breaks out in the barracks — a random piece on each side is destroyed.",
        "rarity": "rare",
        "phase": 2,
        "weight": 1.2,
        "cooldown": 3,
        "tags": ["damage", "chaos"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "destroy", "target": "random_any"},
        ],
    },
    {
        "id": "alchemists_bounty",
        "name": "Alchemist's Bounty",
        "desc": "Your court alchemist finally turns lead into gold — it only took 200 turns.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 25}],
    },
    {
        "id": "landmine",
        "name": "Landmine",
        "desc": "A buried explosive is placed on a random square — step carefully.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 3,
        "tags": ["board", "damage"],
        "effects": [{"type": "place_hazard", "hazard_id": "landmine", "duration": 5}],
    },
    {
        "id": "quickstep",
        "name": "Quickstep",
        "desc": "Your pieces move with supernatural speed — take an extra turn immediately.",
        "rarity": "rare",
        "phase": 2,
        "weight": 1.0,
        "cooldown": 5,
        "tags": ["movement", "buff"],
        "effects": [{"type": "extra_turn"}],
    },
    {
        "id": "confusion_hex",
        "name": "Confusion Hex",
        "desc": "A witch cackles from the sidelines and swaps two random pieces on the board.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["chaos", "movement"],
        "effects": [{"type": "swap", "target": "random_any"}],
    },
    {
        "id": "scrap_dealer",
        "name": "Scrap Dealer",
        "desc": "A shady merchant offers to buy your captured pieces for a decent price.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 12}],
    },
    {
        "id": "squire_promotion",
        "name": "Squire Promotion",
        "desc": "A lowly pawn is knighted on the spot and becomes a horse.",
        "rarity": "rare",
        "phase": 2,
        "weight": 1.2,
        "cooldown": 4,
        "tags": ["transform", "buff"],
        "effects": [{"type": "transform", "target": "random_self", "into": "n"}],
    },
    {
        "id": "tripwire",
        "name": "Tripwire",
        "desc": "Thin wires stretch across the board, ready to humiliate the next piece that moves.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.2,
        "cooldown": 2,
        "tags": ["board"],
        "effects": [{"type": "place_hazard", "hazard_id": "tripwire", "duration": 3}],
    },
    {
        "id": "draft_notice",
        "name": "Draft Notice",
        "desc": "Another reluctant pawn is conscripted from the reserves.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.2,
        "cooldown": 2,
        "tags": ["summon"],
        "effects": [{"type": "spawn", "piece": "p", "square": "random_empty"}],
    },
    {
        "id": "charity_gala",
        "name": "Charity Gala",
        "desc": "Both kings host a gala in the middle of war — somehow everyone profits.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.5,
        "cooldown": 1,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "both", "amount": 10}],
    },
    {
        "id": "opportunist_strike",
        "name": "Opportunist Strike",
        "desc": "Your rook seizes an opening and rams into an enemy piece.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 2,
        "tags": ["damage"],
        "effects": [{"type": "destroy", "target": "random_enemy"}],
    },
    {
        "id": "fog_of_war",
        "name": "Fog of War",
        "desc": "A thick fog rolls in — both players draw an extra chaos card.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 3,
        "tags": ["chaos"],
        "effects": [{"type": "draw_cards", "count": 2}],
    },
    {
        "id": "market_crash",
        "name": "Market Crash",
        "desc": "The pawn economy collapses — both sides lose gold but chaos surges.",
        "rarity": "rare",
        "phase": 2,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "gold", "player": "both", "amount": -10},
            {"type": "chaos", "player": "both", "amount": 10},
        ],
    },

    # =========================================================================
    # PHASE 3 — Board Manipulation, Stronger Attacks, Transforms (25 cards)
    # =========================================================================
    {
        "id": "gravity_well",
        "name": "Gravity Well",
        "desc": "A localized gravity anomaly yanks an enemy piece to a random square.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.8,
        "cooldown": 2,
        "tags": ["board", "movement"],
        "effects": [{"type": "teleport", "target": "random_enemy"}],
    },
    {
        "id": "bishops_revenge",
        "name": "Bishop's Revenge",
        "desc": "The bishop has had enough of diagonal jokes and transforms into a queen.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 5,
        "tags": ["transform", "buff"],
        "effects": [{"type": "transform", "target": "random_self", "into": "q"}],
    },
    {
        "id": "pit_trap",
        "name": "Pit Trap",
        "desc": "A concealed pit is dug on the board — the next piece to cross it falls in.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.8,
        "cooldown": 3,
        "tags": ["board", "damage"],
        "effects": [{"type": "place_hazard", "hazard_id": "pit_trap", "duration": 4}],
    },
    {
        "id": "necromancers_call",
        "name": "Necromancer's Call",
        "desc": "A hooded figure raises a fallen piece from the graveyard — it serves you now.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 5,
        "tags": ["summon"],
        "effects": [{"type": "resurrect", "side": "self"}],
    },
    {
        "id": "cursed_ground",
        "name": "Cursed Ground",
        "desc": "Dark energy seeps from the earth, creating a hazardous zone on the board.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["board", "damage"],
        "effects": [{"type": "place_hazard", "hazard_id": "cursed_ground", "duration": 4}],
    },
    {
        "id": "horse_thief",
        "name": "Horse Thief",
        "desc": "An enemy knight is demoted to a lowly pawn — the horse ran away.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["transform", "debuff"],
        "effects": [{"type": "transform", "target": "random_enemy", "into": "b"}],
    },
    {
        "id": "pirate_raid",
        "name": "Pirate Raid",
        "desc": "Pirates storm the board from the flanks, stealing gold and causing mayhem.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.2,
        "cooldown": 3,
        "tags": ["economy", "damage"],
        "effects": [
            {"type": "steal_gold", "amount": 15},
            {"type": "destroy", "target": "random_enemy"},
        ],
    },
    {
        "id": "time_skip",
        "name": "Time Skip",
        "desc": "The fabric of time tears — your opponent loses their next turn entirely.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["debuff", "chaos"],
        "effects": [{"type": "skip_turn", "player": "opponent"}],
    },
    {
        "id": "clone_protocol",
        "name": "Clone Protocol",
        "desc": "Forbidden magic duplicates one of your pieces — the copy is slightly confused.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 5,
        "tags": ["summon", "chaos"],
        "effects": [{"type": "clone", "target": "self_piece"}],
    },
    {
        "id": "electromagnetic_pulse",
        "name": "Electromagnetic Pulse",
        "desc": "A pulse scrambles the board — two random enemy pieces are frozen solid.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["debuff", "area"],
        "effects": [
            {"type": "freeze", "target": "random_enemy", "duration": 2},
            {"type": "freeze", "target": "random_enemy", "duration": 2},
        ],
    },
    {
        "id": "rook_launcher",
        "name": "Rook Launcher",
        "desc": "A trebuchet flings a fresh rook onto the battlefield — incoming!",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["summon"],
        "effects": [{"type": "spawn", "piece": "r", "square": "random_empty"}],
    },
    {
        "id": "reverse_polarity",
        "name": "Reverse Polarity",
        "desc": "Magnetic fields flip — two random pieces on the board swap positions.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "swap", "target": "random_any"},
            {"type": "swap", "target": "random_any"},
        ],
    },
    {
        "id": "lava_flow",
        "name": "Lava Flow",
        "desc": "Molten rock bubbles up from beneath the board, scorching a hazardous trail.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["board", "damage", "area"],
        "effects": [{"type": "place_hazard", "hazard_id": "lava_flow", "duration": 5}],
    },
    {
        "id": "shadow_knight",
        "name": "Shadow Knight",
        "desc": "A knight made of pure darkness materializes on your side of the board.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["summon"],
        "effects": [{"type": "spawn", "piece": "n", "square": "random_empty"}],
    },
    {
        "id": "polymorph",
        "name": "Polymorph",
        "desc": "An enemy piece is turned into a harmless pawn by a cackling wizard.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["transform", "debuff"],
        "effects": [{"type": "transform", "target": "random_enemy", "into": "n"}],
    },
    {
        "id": "dimensional_rift",
        "name": "Dimensional Rift",
        "desc": "A rift in spacetime teleports one of your pieces and one of theirs to random squares.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
        ],
    },
    {
        "id": "saboteurs_gambit",
        "name": "Saboteur's Gambit",
        "desc": "A spy plants explosives — a hazard appears and an enemy piece is frozen.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["board", "debuff"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "explosives", "duration": 3},
            {"type": "freeze", "target": "random_enemy", "duration": 2},
        ],
    },
    {
        "id": "bounty_hunter",
        "name": "Bounty Hunter",
        "desc": "A mercenary arrives, destroys an enemy, and sends you the invoice plus profit.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["damage", "economy"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "gold", "player": "self", "amount": 10},
        ],
    },
    {
        "id": "wild_mutation",
        "name": "Wild Mutation",
        "desc": "Chaotic radiation warps one of your pieces into a bishop — it seems fine with this.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["transform", "chaos"],
        "effects": [{"type": "transform", "target": "random_self", "into": "b"}],
    },
    {
        "id": "quicksand",
        "name": "Quicksand",
        "desc": "A patch of quicksand appears — any piece that steps in gets stuck.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["board"],
        "effects": [{"type": "place_hazard", "hazard_id": "quicksand", "duration": 4}],
    },
    {
        "id": "highway_robbery",
        "name": "Highway Robbery",
        "desc": "Bandits waylay the opponent's supply line and divert their gold to you.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["economy"],
        "effects": [{"type": "steal_gold", "amount": 25}],
    },
    {
        "id": "siren_song",
        "name": "Siren Song",
        "desc": "A haunting melody lures an enemy piece away from its post to a random location.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["movement", "debuff"],
        "effects": [{"type": "teleport", "target": "random_enemy"}],
    },
    {
        "id": "arms_dealer",
        "name": "Arms Dealer",
        "desc": "A shady figure sells you a knight at a discount — no questions asked.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["summon", "economy"],
        "effects": [
            {"type": "spawn", "piece": "n", "square": "random_empty"},
            {"type": "gold", "player": "self", "amount": -10},
        ],
    },
    {
        "id": "chaos_lottery",
        "name": "Chaos Lottery",
        "desc": "The chaos gods spin a wheel — draw three extra cards and hope for the best.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["chaos"],
        "effects": [{"type": "draw_cards", "count": 3}],
    },
    {
        "id": "fortify",
        "name": "Fortify",
        "desc": "Your defensive line hardens — two pieces gain temporary shields.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 3,
        "tags": ["defense", "buff"],
        "effects": [
            {"type": "shield", "target": "random_self", "duration": 3},
            {"type": "shield", "target": "random_self", "duration": 3},
        ],
    },

    # =========================================================================
    # PHASE 4 — Powerful Attacks, Area Effects, Epic Abilities (20 cards)
    # =========================================================================
    {
        "id": "meteor_shower",
        "name": "Meteor Shower",
        "desc": "Flaming rocks rain from the sky, obliterating two enemy pieces on impact.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 6,
        "tags": ["damage", "area"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "destroy", "target": "random_enemy"},
        ],
    },
    {
        "id": "dragon_flyby",
        "name": "Dragon Flyby",
        "desc": "A dragon swoops across the board, incinerating an enemy piece and leaving fire behind.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 6,
        "tags": ["damage", "board"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "place_hazard", "hazard_id": "dragonfire", "duration": 4},
        ],
    },
    {
        "id": "dark_ritual",
        "name": "Dark Ritual",
        "desc": "You sacrifice a pawn to the void and summon a queen from the abyss.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 8,
        "tags": ["summon", "transform"],
        "effects": [
            {"type": "destroy", "target": "all_pawns"},
            {"type": "spawn", "piece": "q", "square": "random_empty"},
        ],
    },
    {
        "id": "orbital_laser",
        "name": "Orbital Laser",
        "desc": "A satellite locks on and vaporizes a chosen enemy piece from orbit.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 7,
        "tags": ["damage"],
        "effects": [{"type": "destroy", "target": "chosen_piece"}],
    },
    {
        "id": "blizzard",
        "name": "Blizzard",
        "desc": "An arctic blizzard engulfs the board, freezing three enemy pieces in ice.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 6,
        "tags": ["debuff", "area"],
        "effects": [
            {"type": "freeze", "target": "random_enemy", "duration": 3},
            {"type": "freeze", "target": "random_enemy", "duration": 3},
            {"type": "freeze", "target": "random_enemy", "duration": 3},
        ],
    },
    {
        "id": "grand_heist",
        "name": "Grand Heist",
        "desc": "Your bishop leads an elaborate heist, stealing a fortune from the opponent.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 6,
        "tags": ["economy"],
        "effects": [{"type": "steal_gold", "amount": 40}],
    },
    {
        "id": "earthquake",
        "name": "Earthquake",
        "desc": "The board shakes violently — every piece teleports to a new random position.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["chaos", "movement", "area"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
        ],
    },
    {
        "id": "temporal_paradox",
        "name": "Temporal Paradox",
        "desc": "Time folds in on itself — you take two extra turns while your opponent stares blankly.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.4,
        "cooldown": 8,
        "tags": ["chaos", "buff"],
        "effects": [
            {"type": "extra_turn"},
            {"type": "extra_turn"},
        ],
    },
    {
        "id": "pawn_rebellion",
        "name": "Pawn Rebellion",
        "desc": "The enemy pawns revolt — all enemy pawns are destroyed in the uprising.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 7,
        "tags": ["damage", "chaos"],
        "effects": [{"type": "destroy", "target": "all_pawns"}],
    },
    {
        "id": "summoning_circle",
        "name": "Summoning Circle",
        "desc": "A glowing pentagram appears and spits out a rook and a knight onto your side.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 7,
        "tags": ["summon"],
        "effects": [
            {"type": "spawn", "piece": "r", "square": "random_empty"},
            {"type": "spawn", "piece": "n", "square": "random_empty"},
        ],
    },
    {
        "id": "witch_hex",
        "name": "Witch's Hex",
        "desc": "A cackling witch curses an enemy piece, transforming it into a lowly pawn.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["transform", "debuff"],
        "effects": [{"type": "transform", "target": "random_enemy", "into": "b"}],
    },
    {
        "id": "war_chest",
        "name": "War Chest",
        "desc": "You unearth a buried war chest containing a king's ransom in gold.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["economy"],
        "effects": [{"type": "gold", "player": "self", "amount": 50}],
    },
    {
        "id": "void_snare",
        "name": "Void Snare",
        "desc": "Tendrils of void energy freeze two enemies and place a hazard where they stood.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 7,
        "tags": ["debuff", "board"],
        "effects": [
            {"type": "freeze", "target": "random_enemy", "duration": 3},
            {"type": "freeze", "target": "random_enemy", "duration": 3},
            {"type": "place_hazard", "hazard_id": "void_zone", "duration": 4},
        ],
    },
    {
        "id": "doppelganger",
        "name": "Doppelgänger",
        "desc": "A perfect clone of your strongest piece steps out of a mirror onto the board.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 7,
        "tags": ["summon", "chaos"],
        "effects": [{"type": "clone", "target": "self_piece"}],
    },
    {
        "id": "scorched_earth",
        "name": "Scorched Earth",
        "desc": "You set fire to everything — two hazard zones and one enemy piece destroyed.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["damage", "board", "area"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "place_hazard", "hazard_id": "wildfire", "duration": 4},
            {"type": "place_hazard", "hazard_id": "wildfire", "duration": 4},
        ],
    },
    {
        "id": "mass_conscription",
        "name": "Mass Conscription",
        "desc": "You empty the taverns and press-gang everyone — three pawns materialize.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["summon"],
        "effects": [
            {"type": "spawn", "piece": "p", "square": "random_empty"},
            {"type": "spawn", "piece": "p", "square": "random_empty"},
            {"type": "spawn", "piece": "p", "square": "random_empty"},
        ],
    },
    {
        "id": "frozen_throne",
        "name": "Frozen Throne",
        "desc": "An icy curse locks down the opponent's most powerful piece for four turns.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 7,
        "tags": ["debuff"],
        "effects": [{"type": "freeze", "target": "enemy_piece", "duration": 4}],
    },
    {
        "id": "lightning_storm",
        "name": "Lightning Storm",
        "desc": "Bolts of lightning arc across the board, destroying two random pieces from either side.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["damage", "chaos", "area"],
        "effects": [
            {"type": "destroy", "target": "random_any"},
            {"type": "destroy", "target": "random_any"},
        ],
    },
    {
        "id": "ressurection_altar",
        "name": "Resurrection Altar",
        "desc": "An ancient altar glows — your most recently captured piece returns from the dead.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 7,
        "tags": ["summon"],
        "effects": [{"type": "resurrect", "side": "self"}],
    },
    {
        "id": "chaos_tax",
        "name": "Chaos Tax",
        "desc": "The chaos gods demand tribute — gold flows from the opponent while chaos energy surges.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 5,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "steal_gold", "amount": 25},
            {"type": "chaos", "player": "self", "amount": 15},
        ],
    },

    # =========================================================================
    # PHASE 5 — Absolute Chaos, Legendary, Multi-Effect (15 cards)
    # =========================================================================
    {
        "id": "armageddon",
        "name": "Armageddon",
        "desc": "The sky splits open and holy fire rains down, annihilating all pawns and leaving the board ablaze.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["damage", "area", "chaos", "board"],
        "effects": [
            {"type": "destroy", "target": "all_pawns"},
            {"type": "place_hazard", "hazard_id": "hellfire", "duration": 6},
            {"type": "chaos", "player": "both", "amount": 20},
        ],
    },
    {
        "id": "the_rapture",
        "name": "The Rapture",
        "desc": "Every piece on the board is teleported to a random square as reality unravels.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["chaos", "movement", "area"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
        ],
    },
    {
        "id": "hand_of_god",
        "name": "Hand of God",
        "desc": "A colossal hand descends from the clouds, flicks away two enemy pieces, and drops a queen on your side.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["damage", "summon", "chaos"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "destroy", "target": "random_enemy"},
            {"type": "spawn", "piece": "q", "square": "random_empty"},
        ],
    },
    {
        "id": "pandoras_box",
        "name": "Pandora's Box",
        "desc": "You open the forbidden box — five chaos cards are drawn and the board screams.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["chaos"],
        "effects": [
            {"type": "draw_cards", "count": 5},
            {"type": "chaos", "player": "both", "amount": 25},
        ],
    },
    {
        "id": "black_hole",
        "name": "Black Hole",
        "desc": "A singularity tears open on the board, destroying everything in a 3-square radius and warping time.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["damage", "area", "chaos", "board"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 3},
            {"type": "place_hazard", "hazard_id": "singularity", "duration": 6},
            {"type": "skip_turn", "player": "opponent"},
        ],
    },
    {
        "id": "total_war",
        "name": "Total War",
        "desc": "Both armies go berserk — three random pieces on each side are destroyed in mutual carnage.",
        "rarity": "epic",
        "phase": 5,
        "weight": 0.4,
        "cooldown": 8,
        "tags": ["damage", "chaos", "area"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "destroy", "target": "random_enemy"},
            {"type": "destroy", "target": "random_enemy"},
            {"type": "destroy", "target": "random_any"},
            {"type": "destroy", "target": "random_any"},
            {"type": "destroy", "target": "random_any"},
        ],
    },
    {
        "id": "wizard_duel",
        "name": "Wizard Duel",
        "desc": "Two wizards appear, transform pieces on both sides, then vanish in a puff of smoke.",
        "rarity": "epic",
        "phase": 5,
        "weight": 0.4,
        "cooldown": 8,
        "tags": ["transform", "chaos"],
        "effects": [
            {"type": "transform", "target": "random_self", "into": "q"},
            {"type": "transform", "target": "random_enemy", "into": "q"},
            {"type": "chaos", "player": "both", "amount": 15},
        ],
    },
    {
        "id": "zombie_apocalypse",
        "name": "Zombie Apocalypse",
        "desc": "The graveyard empties — all your captured pieces rise as undead and stagger back onto the board.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["summon", "chaos"],
        "effects": [
            {"type": "resurrect", "side": "self"},
            {"type": "resurrect", "side": "self"},
            {"type": "resurrect", "side": "self"},
            {"type": "chaos", "player": "both", "amount": 10},
        ],
    },
    {
        "id": "nuclear_option",
        "name": "The Nuclear Option",
        "desc": "You push the button — a massive explosion wipes a 4-square radius and irradiates the area.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["damage", "area", "board"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 4},
            {"type": "place_hazard", "hazard_id": "radiation", "duration": 8},
            {"type": "gold", "player": "both", "amount": -20},
        ],
    },
    {
        "id": "kings_gambit_supreme",
        "name": "King's Gambit Supreme",
        "desc": "Your king personally takes the field — extra turn, gold surge, and an enemy piece trembles into oblivion.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 10,
        "tags": ["damage", "economy", "buff"],
        "effects": [
            {"type": "extra_turn"},
            {"type": "gold", "player": "self", "amount": 40},
            {"type": "destroy", "target": "random_enemy"},
        ],
    },
    {
        "id": "reality_shatter",
        "name": "Reality Shatter",
        "desc": "The laws of chess break entirely — pieces swap, teleport, freeze, and gold rains from the sky.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["chaos", "movement", "economy", "debuff"],
        "effects": [
            {"type": "swap", "target": "random_any"},
            {"type": "swap", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "freeze", "target": "random_enemy", "duration": 3},
            {"type": "gold", "player": "both", "amount": 20},
        ],
    },
    {
        "id": "army_of_clones",
        "name": "Army of Clones",
        "desc": "A deranged alchemist clones your best piece three times — the copies are enthusiastic if short-lived.",
        "rarity": "epic",
        "phase": 5,
        "weight": 0.4,
        "cooldown": 8,
        "tags": ["summon", "chaos"],
        "effects": [
            {"type": "clone", "target": "self_piece"},
            {"type": "clone", "target": "self_piece"},
            {"type": "clone", "target": "self_piece"},
        ],
    },
    {
        "id": "the_great_swap",
        "name": "The Great Swap",
        "desc": "Every piece on the board switches allegiance for one bewildering moment, then chaos reigns.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 10,
        "tags": ["chaos", "movement"],
        "effects": [
            {"type": "swap", "target": "random_any"},
            {"type": "swap", "target": "random_any"},
            {"type": "swap", "target": "random_any"},
            {"type": "chaos", "player": "both", "amount": 30},
        ],
    },
    {
        "id": "extinction_event",
        "name": "Extinction Event",
        "desc": "An asteroid the size of a rook hurtles toward the board — nothing will ever be the same.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.15,
        "cooldown": 15,
        "tags": ["damage", "area", "chaos", "board"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 5},
            {"type": "destroy", "target": "random_any", "radius": 5},
            {"type": "place_hazard", "hazard_id": "crater", "duration": 10},
            {"type": "chaos", "player": "both", "amount": 50},
        ],
    },
    {
        "id": "final_gambit",
        "name": "Final Gambit",
        "desc": "You wager everything — destroy all your pawns, gain massive gold, summon a queen, and skip the opponent's turn.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.15,
        "cooldown": 15,
        "tags": ["damage", "economy", "summon", "chaos"],
        "effects": [
            {"type": "destroy", "target": "all_pawns"},
            {"type": "gold", "player": "self", "amount": 100},
            {"type": "spawn", "piece": "q", "square": "random_empty"},
            {"type": "skip_turn", "player": "opponent"},
        ],
    },
]
