EVENTS = [
    # =========================================================================
    # PHASE 1-2: MILD EVENTS (12)
    # =========================================================================
    {
        "id": "minor_tremor",
        "name": "Minor Tremor",
        "desc": "A small earthquake rattles the board, displacing a random piece.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 2,
        "tags": ["movement", "environmental"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {},
    },
    {
        "id": "gold_dust_wind",
        "name": "Gold Dust Wind",
        "desc": "A shimmering breeze scatters gold coins across the battlefield.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.5,
        "cooldown": 2,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "both", "amount": 3},
        ],
        "meta": {},
    },
    {
        "id": "fog_wisp",
        "name": "Fog Wisp",
        "desc": "A thin mist rolls in, briefly obscuring part of the board.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 3,
        "tags": ["environmental", "hazard"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "fog", "duration": 2},
        ],
        "meta": {"duration": 2},
    },
    {
        "id": "pawn_skirmish",
        "name": "Pawn Skirmish",
        "desc": "Two pawns get into a scuffle and one is knocked to a new square.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 2,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {},
    },
    {
        "id": "tax_collector",
        "name": "Tax Collector",
        "desc": "A greedy tax collector skims gold from both players.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 3,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "both", "amount": -2},
        ],
        "meta": {},
    },
    {
        "id": "stray_arrow",
        "name": "Stray Arrow",
        "desc": "An arrow from nowhere strikes down a random piece on the board.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["damage", "destruction"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 0},
        ],
        "meta": {},
    },
    {
        "id": "lucky_coin",
        "name": "Lucky Coin",
        "desc": "You find a lucky coin buried in the battlefield dirt.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 2,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 4},
        ],
        "meta": {},
    },
    {
        "id": "slippery_ice_patch",
        "name": "Slippery Ice Patch",
        "desc": "A patch of ice forms on the board, making movement treacherous.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 3,
        "tags": ["hazard", "environmental"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "ice", "duration": 2},
        ],
        "meta": {"duration": 2},
    },
    {
        "id": "wandering_merchant",
        "name": "Wandering Merchant",
        "desc": "A travelling merchant passes through, tossing gold to the active player.",
        "rarity": "uncommon",
        "phase": 1,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 5},
        ],
        "meta": {},
    },
    {
        "id": "recruit_conscript",
        "name": "Recruit Conscript",
        "desc": "A fresh conscript joins your army as a pawn on a random empty square.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 4,
        "tags": ["chaos"],
        "effects": [
            {"type": "spawn", "piece": "p", "square": "random_empty"},
        ],
        "meta": {},
    },
    {
        "id": "ember_shower",
        "name": "Ember Shower",
        "desc": "Tiny embers rain from the sky, singeing a random enemy piece.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["damage", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 0},
        ],
        "meta": {},
    },
    {
        "id": "mystic_swap",
        "name": "Mystic Swap",
        "desc": "Two random pieces on the board magically exchange positions.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "swap", "target": "random_any"},
        ],
        "meta": {},
    },

    # =========================================================================
    # PHASE 2-3: MODERATE EVENTS (18)
    # =========================================================================
    {
        "id": "earthquake",
        "name": "Earthquake",
        "desc": "The ground shakes violently, teleporting several pieces to new positions.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 4,
        "tags": ["movement", "environmental", "chaos"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {},
    },
    {
        "id": "pirate_raid",
        "name": "Pirate Raid",
        "desc": "Pirates storm the board, stealing gold from your opponent.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "gold", "player": "opponent", "amount": -5},
            {"type": "gold", "player": "self", "amount": 3},
        ],
        "meta": {},
    },
    {
        "id": "volcanic_vent",
        "name": "Volcanic Vent",
        "desc": "A volcanic vent erupts from the board, leaving a hazardous lava pool.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["hazard", "environmental", "destruction"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "lava", "duration": 3},
            {"type": "destroy", "target": "random_any", "radius": 1},
        ],
        "meta": {"duration": 3},
    },
    {
        "id": "gravity_hiccup",
        "name": "Gravity Hiccup",
        "desc": "Gravity briefly reverses, flinging a piece across the board.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {},
    },
    {
        "id": "plague_rats",
        "name": "Plague Rats",
        "desc": "A swarm of plague rats infests the board, freezing a piece in fear.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["hazard", "environmental"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 2},
            {"type": "place_hazard", "hazard_id": "plague", "duration": 2},
        ],
        "meta": {"duration": 2},
    },
    {
        "id": "time_hiccup",
        "name": "Time Hiccup",
        "desc": "A minor temporal distortion freezes a random enemy piece in time.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["chaos"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 2},
        ],
        "meta": {},
    },
    {
        "id": "pawn_rebellion",
        "name": "Pawn Rebellion",
        "desc": "A pawn grows tired of servitude and transforms into a knight.",
        "rarity": "rare",
        "phase": 2,
        "weight": 1.5,
        "cooldown": 5,
        "tags": ["transform", "chaos"],
        "effects": [
            {"type": "transform", "target": "random_any", "into": "n"},
        ],
        "meta": {},
    },
    {
        "id": "dragon_flyby",
        "name": "Dragon Flyby",
        "desc": "A dragon swoops over the battlefield, scorching a random enemy piece.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 5,
        "tags": ["damage", "destruction"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 1},
        ],
        "meta": {},
    },
    {
        "id": "gold_rush",
        "name": "Gold Rush",
        "desc": "A vein of gold is discovered beneath the board, enriching both players.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "both", "amount": 6},
        ],
        "meta": {},
    },
    {
        "id": "frost_wind",
        "name": "Frost Wind",
        "desc": "An icy gale sweeps the board, freezing a random piece solid.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["environmental", "hazard"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 2},
        ],
        "meta": {},
    },
    {
        "id": "solar_flicker",
        "name": "Solar Flicker",
        "desc": "A burst of solar energy supercharges a random piece, adding chaos energy.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["chaos", "environmental"],
        "effects": [
            {"type": "chaos", "player": "both", "amount": 3},
        ],
        "meta": {},
    },
    {
        "id": "dimensional_flicker",
        "name": "Dimensional Flicker",
        "desc": "Reality glitches momentarily, swapping two random pieces between positions.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.2,
        "cooldown": 5,
        "tags": ["teleport", "chaos"],
        "effects": [
            {"type": "swap", "target": "random_any"},
            {"type": "swap", "target": "random_any"},
        ],
        "meta": {},
    },
    {
        "id": "necromantic_whisper",
        "name": "Necromantic Whisper",
        "desc": "Dark magic raises a fallen pawn from the dead onto a random empty square.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.2,
        "cooldown": 5,
        "tags": ["chaos"],
        "effects": [
            {"type": "spawn", "piece": "p", "square": "random_empty"},
        ],
        "meta": {},
    },
    {
        "id": "wormhole_blip",
        "name": "Wormhole Blip",
        "desc": "A small wormhole opens and sucks an enemy piece to a random location.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["teleport", "chaos"],
        "effects": [
            {"type": "teleport", "target": "random_enemy"},
        ],
        "meta": {},
    },
    {
        "id": "meteor_pebble",
        "name": "Meteor Pebble",
        "desc": "A small meteorite strikes the board, destroying a random piece nearby.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["damage", "destruction", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 1},
        ],
        "meta": {},
    },
    {
        "id": "treasure_goblin",
        "name": "Treasure Goblin",
        "desc": "A treasure goblin dashes across the board, dropping gold for the active player.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.2,
        "cooldown": 5,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 8},
        ],
        "meta": {},
    },
    {
        "id": "quicksand_pit",
        "name": "Quicksand Pit",
        "desc": "Quicksand appears on the board, trapping and freezing any piece that enters.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["hazard", "board"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "quicksand", "duration": 3},
        ],
        "meta": {"duration": 3},
    },
    {
        "id": "phantom_cavalry",
        "name": "Phantom Cavalry",
        "desc": "Ghostly horsemen charge across the board, swapping pieces and spreading dread.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.2,
        "cooldown": 5,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "swap", "target": "random_any"},
            {"type": "chaos", "player": "both", "amount": 2},
        ],
        "meta": {},
    },

    # =========================================================================
    # PHASE 3-4: STRONG EVENTS (18)
    # =========================================================================
    {
        "id": "meteor_shower",
        "name": "Meteor Shower",
        "desc": "A barrage of meteors rains down, destroying pieces in a wide radius.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 6,
        "tags": ["damage", "destruction", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "destroy", "target": "random_any", "radius": 1},
        ],
        "meta": {},
    },
    {
        "id": "gravity_inversion",
        "name": "Gravity Inversion",
        "desc": "Gravity flips entirely, teleporting all pieces to mirrored positions.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 6,
        "tags": ["movement", "chaos", "board"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {},
    },
    {
        "id": "dragon_attack",
        "name": "Dragon Attack",
        "desc": "A fearsome dragon descends and incinerates enemy pieces in a fiery blast.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 6,
        "tags": ["damage", "destruction"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 2},
        ],
        "meta": {},
    },
    {
        "id": "volcanic_eruption",
        "name": "Volcanic Eruption",
        "desc": "The board's volcano erupts, spreading lava and destroying nearby pieces.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 6,
        "tags": ["destruction", "hazard", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "place_hazard", "hazard_id": "lava", "duration": 4},
        ],
        "meta": {"duration": 4},
    },
    {
        "id": "time_rift",
        "name": "Time Rift",
        "desc": "A crack in time freezes multiple pieces and warps the flow of combat.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 6,
        "tags": ["chaos"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "freeze", "target": "random_any", "duration": 2},
        ],
        "meta": {},
    },
    {
        "id": "ice_age_onset",
        "name": "Ice Age Onset",
        "desc": "A sudden cold snap covers the board in ice, freezing pieces and creating hazards.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 6,
        "tags": ["environmental", "hazard"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "place_hazard", "hazard_id": "ice", "duration": 4},
        ],
        "meta": {"duration": 4},
    },
    {
        "id": "solar_flare",
        "name": "Solar Flare",
        "desc": "A massive solar flare scorches the board, dealing chaos damage to both sides.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["chaos", "environmental", "damage"],
        "effects": [
            {"type": "chaos", "player": "both", "amount": 5},
            {"type": "destroy", "target": "random_any", "radius": 1},
        ],
        "meta": {},
    },
    {
        "id": "necromantic_surge",
        "name": "Necromantic Surge",
        "desc": "Dark energy floods the board, raising fallen warriors and transforming the living.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["transform", "chaos"],
        "effects": [
            {"type": "spawn", "piece": "p", "square": "random_empty"},
            {"type": "spawn", "piece": "p", "square": "random_empty"},
            {"type": "transform", "target": "random_any", "into": "n"},
        ],
        "meta": {},
    },
    {
        "id": "pirate_invasion",
        "name": "Pirate Invasion",
        "desc": "A full pirate fleet attacks, plundering massive gold and destroying a piece.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["economy", "destruction", "chaos"],
        "effects": [
            {"type": "gold", "player": "opponent", "amount": -8},
            {"type": "gold", "player": "self", "amount": 5},
            {"type": "destroy", "target": "random_enemy", "radius": 0},
        ],
        "meta": {},
    },
    {
        "id": "wormhole_storm",
        "name": "Wormhole Storm",
        "desc": "Multiple wormholes tear open, teleporting pieces all over the board.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["teleport", "chaos", "board"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_enemy"},
        ],
        "meta": {},
    },
    {
        "id": "plague_outbreak",
        "name": "Plague Outbreak",
        "desc": "A deadly plague sweeps across the board, freezing and damaging random pieces.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["hazard", "damage", "environmental"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "destroy", "target": "random_any", "radius": 1},
            {"type": "place_hazard", "hazard_id": "plague", "duration": 3},
        ],
        "meta": {"duration": 3},
    },
    {
        "id": "fog_of_war",
        "name": "Fog of War",
        "desc": "An impenetrable fog blankets the battlefield, hiding all pieces from view.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 5,
        "tags": ["board", "environmental"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "fog", "duration": 4},
        ],
        "meta": {"duration": 4},
    },
    {
        "id": "pawn_uprising",
        "name": "Pawn Uprising",
        "desc": "All pawns rebel against their masters, transforming one into a queen.",
        "rarity": "epic",
        "phase": 3,
        "weight": 0.8,
        "cooldown": 7,
        "tags": ["transform", "chaos"],
        "effects": [
            {"type": "transform", "target": "random_any", "into": "q"},
            {"type": "chaos", "player": "both", "amount": 4},
        ],
        "meta": {},
    },
    {
        "id": "dimensional_tear",
        "name": "Dimensional Tear",
        "desc": "A rift between dimensions opens, scattering pieces and spawning chaos energy.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 7,
        "tags": ["teleport", "chaos", "board"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_enemy"},
            {"type": "chaos", "player": "both", "amount": 5},
        ],
        "meta": {},
    },
    {
        "id": "knights_errant",
        "name": "Knights Errant",
        "desc": "Wandering knights arrive to join the fray, spawning on empty squares.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 5,
        "tags": ["chaos"],
        "effects": [
            {"type": "spawn", "piece": "n", "square": "random_empty"},
            {"type": "spawn", "piece": "n", "square": "random_empty"},
        ],
        "meta": {},
    },
    {
        "id": "cursed_ground",
        "name": "Cursed Ground",
        "desc": "The earth itself becomes cursed, placing a persistent hazard on the board.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["hazard", "board", "environmental"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "curse", "duration": 5},
            {"type": "destroy", "target": "random_any", "radius": 0},
        ],
        "meta": {"duration": 5},
    },
    {
        "id": "thunderstrike",
        "name": "Thunderstrike",
        "desc": "Lightning crashes onto the board, obliterating a piece and electrifying the area.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["damage", "destruction", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 1},
            {"type": "place_hazard", "hazard_id": "lightning", "duration": 2},
        ],
        "meta": {"duration": 2},
    },
    {
        "id": "treasure_hoard",
        "name": "Treasure Hoard",
        "desc": "An ancient treasure hoard is unearthed, showering the active player with gold.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 7,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 12},
        ],
        "meta": {},
    },

    # =========================================================================
    # PHASE 4-5: EXTREME EVENTS (12)
    # =========================================================================
    {
        "id": "armageddon",
        "name": "Armageddon",
        "desc": "The ultimate cataclysm strikes, destroying all pawns on the board.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["damage", "destruction", "chaos"],
        "effects": [
            {"type": "destroy", "target": "all_pawns", "radius": 0},
        ],
        "meta": {},
    },
    {
        "id": "dimensional_collapse",
        "name": "Dimensional Collapse",
        "desc": "Reality itself collapses, teleporting every piece and flooding the board with chaos.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["teleport", "chaos", "board"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
            {"type": "chaos", "player": "both", "amount": 8},
        ],
        "meta": {},
    },
    {
        "id": "meteor_apocalypse",
        "name": "Meteor Apocalypse",
        "desc": "A cataclysmic meteor storm obliterates huge swathes of the battlefield.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["damage", "destruction", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 3},
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "place_hazard", "hazard_id": "crater", "duration": 5},
        ],
        "meta": {"duration": 5},
    },
    {
        "id": "dragon_rampage",
        "name": "Dragon Rampage",
        "desc": "An ancient dragon goes berserk, laying waste to pieces on both sides.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["damage", "destruction", "chaos"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "destroy", "target": "random_enemy", "radius": 2},
            {"type": "place_hazard", "hazard_id": "fire", "duration": 3},
        ],
        "meta": {"duration": 3},
    },
    {
        "id": "eternal_winter",
        "name": "Eternal Winter",
        "desc": "An endless ice age descends, freezing the entire board and all who stand on it.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["environmental", "hazard", "board"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 4},
            {"type": "freeze", "target": "random_any", "duration": 4},
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "place_hazard", "hazard_id": "ice", "duration": 5},
        ],
        "meta": {"duration": 5},
    },
    {
        "id": "supernova",
        "name": "Supernova",
        "desc": "A dying star explodes, bathing the board in destructive cosmic energy.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["damage", "destruction", "environmental", "chaos"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 3},
            {"type": "chaos", "player": "both", "amount": 10},
        ],
        "meta": {},
    },
    {
        "id": "total_eclipse",
        "name": "Total Eclipse",
        "desc": "The sun vanishes and darkness swallows the board, creating fog and freezing pieces.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 8,
        "tags": ["environmental", "hazard", "board"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "fog", "duration": 5},
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "freeze", "target": "random_any", "duration": 2},
        ],
        "meta": {"duration": 5},
    },
    {
        "id": "ascension",
        "name": "Ascension",
        "desc": "A random pawn is chosen by the gods and ascends into a mighty queen.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 8,
        "tags": ["transform", "chaos"],
        "effects": [
            {"type": "transform", "target": "random_any", "into": "q"},
        ],
        "meta": {},
    },
    {
        "id": "black_hole_rift",
        "name": "Black Hole Rift",
        "desc": "A black hole tears open on the board, destroying and teleporting everything nearby.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 8,
        "tags": ["destruction", "teleport", "chaos"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {},
    },
    {
        "id": "gold_apocalypse",
        "name": "Gold Apocalypse",
        "desc": "The economy collapses and rebuilds; both players lose gold then gain a fortune.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.5,
        "cooldown": 8,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "gold", "player": "both", "amount": -10},
            {"type": "gold", "player": "both", "amount": 15},
        ],
        "meta": {},
    },
    {
        "id": "wrath_of_the_ancients",
        "name": "Wrath of the Ancients",
        "desc": "Ancient spirits awaken in fury, destroying, freezing, and scattering all pieces.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["damage", "destruction", "chaos", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "teleport", "target": "random_any"},
            {"type": "chaos", "player": "both", "amount": 7},
        ],
        "meta": {},
    },
    {
        "id": "ragnarok",
        "name": "Ragnarok",
        "desc": "The twilight of the gods descends, reshaping the entire board in fire and chaos.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["damage", "destruction", "chaos", "board", "hazard"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 3},
            {"type": "destroy", "target": "random_enemy", "radius": 2},
            {"type": "place_hazard", "hazard_id": "fire", "duration": 5},
            {"type": "chaos", "player": "both", "amount": 10},
        ],
        "meta": {"duration": 5},
    },
]
