HAZARDS = [
    # ── Fire ──────────────────────────────────────────────────────
    {
        "id": "ember_tile",
        "name": "Ember Tile",
        "desc": "Singes the piece for 1 damage, leaving it weakened for the next capture attempt.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 0,
        "tags": ["damage", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 4, "visual": (255, 120, 30)},
    },
    {
        "id": "inferno_geyser",
        "name": "Inferno Geyser",
        "desc": "Erupts on landing, destroying the piece and scorching all adjacent squares.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.2,
        "cooldown": 0,
        "tags": ["damage", "trap"],
        "effects": [
            {"type": "destroy", "target": "random_enemy"},
            {"type": "chaos", "player": "self", "amount": 4},
        ],
        "meta": {"duration": 3, "visual": (255, 50, 0)},
    },
    # ── Ice ────────────────────────────────────────────────────────
    {
        "id": "frost_patch",
        "name": "Frost Patch",
        "desc": "Freezes the piece in place for one turn — it cannot move or capture.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 0,
        "tags": ["movement", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 5, "visual": (150, 210, 255)},
    },
    {
        "id": "glacial_slide",
        "name": "Glacial Slide",
        "desc": "The piece slides forward uncontrollably until it hits another piece or the board edge.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.7,
        "cooldown": 0,
        "tags": ["movement", "chaos"],
        "effects": [{"type": "chaos", "player": "self", "amount": 2}],
        "meta": {"duration": 4, "visual": (180, 230, 255)},
    },
    # ── Void ───────────────────────────────────────────────────────
    {
        "id": "void_rift",
        "name": "Void Rift",
        "desc": "The piece is swallowed by the void and removed from play entirely.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 0,
        "tags": ["damage", "trap"],
        "effects": [{"type": "destroy", "target": "random_enemy"}],
        "meta": {"duration": 5, "visual": (40, 0, 80)},
    },
    {
        "id": "null_zone",
        "name": "Null Zone",
        "desc": "Strips the piece of all buffs and mutations while standing on this square.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 0,
        "tags": ["chaos", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 6, "visual": (60, 10, 100)},
    },
    # ── Lava ───────────────────────────────────────────────────────
    {
        "id": "lava_flow",
        "name": "Lava Flow",
        "desc": "Deals heavy damage and spreads to one adjacent empty square each turn.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 0,
        "tags": ["damage", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 3}],
        "meta": {"duration": 4, "visual": (230, 60, 0)},
    },
    {
        "id": "molten_core",
        "name": "Molten Core",
        "desc": "The piece is encased in cooling lava — immobilised for 2 turns but immune to capture.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.25,
        "cooldown": 0,
        "tags": ["movement", "damage", "trap"],
        "effects": [
            {"type": "shield", "target": "random_self", "duration": 2},
            {"type": "chaos", "player": "self", "amount": 2},
        ],
        "meta": {"duration": 3, "visual": (200, 40, 10)},
    },
    # ── Quicksand ──────────────────────────────────────────────────
    {
        "id": "quicksand_pit",
        "name": "Quicksand Pit",
        "desc": "The piece sinks slowly — move it next turn or it is permanently lost.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.7,
        "cooldown": 0,
        "tags": ["movement", "trap"],
        "effects": [{"type": "chaos", "player": "self", "amount": 2}],
        "meta": {"duration": 3, "visual": (190, 170, 110)},
    },
    {
        "id": "sinking_dunes",
        "name": "Sinking Dunes",
        "desc": "Movement range is halved while crossing these treacherous shifting sands.",
        "rarity": "common",
        "phase": 1,
        "weight": 0.9,
        "cooldown": 0,
        "tags": ["movement", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 5, "visual": (210, 190, 130)},
    },
    # ── Thorns ─────────────────────────────────────────────────────
    {
        "id": "thorn_thicket",
        "name": "Thorn Thicket",
        "desc": "Pricks the piece on entry and again each turn it stays, stacking damage.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 0,
        "tags": ["damage", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 6, "visual": (50, 140, 30)},
    },
    {
        "id": "briar_maze",
        "name": "Briar Maze",
        "desc": "Restricts movement to only one adjacent square per turn while entangled.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.65,
        "cooldown": 0,
        "tags": ["movement", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 4, "visual": (70, 110, 20)},
    },
    # ── Gold Mines ─────────────────────────────────────────────────
    {
        "id": "gold_vein",
        "name": "Gold Vein",
        "desc": "Landing here yields a small gold bonus — a welcome break from the chaos.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 0,
        "tags": ["economy", "terrain"],
        "effects": [{"type": "gold", "player": "self", "amount": 10}],
        "meta": {"duration": 5, "visual": (255, 215, 0)},
    },
    {
        "id": "motherlode",
        "name": "Motherlode",
        "desc": "A massive gold deposit — the player gains a fortune but all nearby enemies are alerted.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.35,
        "cooldown": 0,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 30},
            {"type": "chaos", "player": "opponent", "amount": 2},
        ],
        "meta": {"duration": 3, "visual": (255, 200, 50)},
    },
    # ── Wormholes ──────────────────────────────────────────────────
    {
        "id": "wormhole_alpha",
        "name": "Wormhole Alpha",
        "desc": "Teleports the piece to a random empty square on the opposite half of the board.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 0,
        "tags": ["teleport", "chaos"],
        "effects": [{"type": "chaos", "player": "self", "amount": 2}],
        "meta": {"duration": 8, "visual": (100, 0, 200)},
    },
    {
        "id": "unstable_portal",
        "name": "Unstable Portal",
        "desc": "Teleports the piece and a random enemy piece to swapped positions.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.35,
        "cooldown": 0,
        "tags": ["teleport", "chaos"],
        "effects": [{"type": "chaos", "player": "self", "amount": 3}],
        "meta": {"duration": 4, "visual": (130, 20, 230)},
    },
    # ── Cursed Ground ──────────────────────────────────────────────
    {
        "id": "cursed_soil",
        "name": "Cursed Soil",
        "desc": "The piece gains a random debuff mutation that lasts until it leaves the area.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 0,
        "tags": ["chaos", "trap"],
        "effects": [{"type": "chaos", "player": "self", "amount": 2}],
        "meta": {"duration": 5, "visual": (80, 60, 80)},
    },
    {
        "id": "hex_circle",
        "name": "Hex Circle",
        "desc": "Curses the piece so that its next capture attempt automatically fails.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 0,
        "tags": ["chaos", "trap", "damage"],
        "effects": [{"type": "chaos", "player": "self", "amount": 3}],
        "meta": {"duration": 3, "visual": (100, 0, 60)},
    },
    # ── Enchanted Tiles ────────────────────────────────────────────
    {
        "id": "blessing_stone",
        "name": "Blessing Stone",
        "desc": "Grants the piece a temporary shield that blocks one capture attempt.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 0,
        "tags": ["terrain"],
        "effects": [{"type": "shield", "target": "random_self", "duration": 3}],
        "meta": {"duration": 4, "visual": (220, 240, 255)},
    },
    {
        "id": "arcane_amplifier",
        "name": "Arcane Amplifier",
        "desc": "Doubles the effect of the next card played while a friendly piece stands here.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.2,
        "cooldown": 0,
        "tags": ["terrain", "chaos"],
        "effects": [{"type": "draw_cards", "count": 2}],
        "meta": {"duration": 3, "visual": (200, 180, 255)},
    },
    # ── Acid Pools ─────────────────────────────────────────────────
    {
        "id": "acid_puddle",
        "name": "Acid Puddle",
        "desc": "Slowly dissolves the piece — it is destroyed if it stays for three consecutive turns.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.65,
        "cooldown": 0,
        "tags": ["damage", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 2}],
        "meta": {"duration": 6, "visual": (130, 230, 30)},
    },
    {
        "id": "corrosion_lake",
        "name": "Corrosion Lake",
        "desc": "Pieces passing through lose their mutation and revert to their base form.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.35,
        "cooldown": 0,
        "tags": ["damage", "transform", "terrain"],
        "effects": [{"type": "chaos", "player": "self", "amount": 3}],
        "meta": {"duration": 5, "visual": (90, 200, 10)},
    },
    # ── Gravity Wells ──────────────────────────────────────────────
    {
        "id": "gravity_well",
        "name": "Gravity Well",
        "desc": "Pulls any piece that moves within two squares towards this tile involuntarily.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 0,
        "tags": ["movement", "chaos"],
        "effects": [{"type": "chaos", "player": "self", "amount": 2}],
        "meta": {"duration": 6, "visual": (30, 30, 60)},
    },
    {
        "id": "singularity",
        "name": "Singularity",
        "desc": "An inescapable gravity trap — any piece landing here is removed from the game.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.1,
        "cooldown": 0,
        "tags": ["damage", "trap"],
        "effects": [{"type": "destroy", "target": "random_enemy"}],
        "meta": {"duration": 3, "visual": (10, 0, 30)},
    },
    # ── Mirror Tiles ───────────────────────────────────────────────
    {
        "id": "mirror_shard",
        "name": "Mirror Shard",
        "desc": "Reflects the piece's movement direction, sending it the opposite way.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.55,
        "cooldown": 0,
        "tags": ["movement", "chaos"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 7, "visual": (200, 200, 220)},
    },
    {
        "id": "hall_of_mirrors",
        "name": "Hall of Mirrors",
        "desc": "Creates a phantom copy of the piece that mimics its moves for two turns.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.2,
        "cooldown": 0,
        "tags": ["chaos", "transform"],
        "effects": [{"type": "spawn", "piece": "n", "square": "random_empty"}],
        "meta": {"duration": 3, "visual": (210, 210, 240)},
    },
    # ── Shock Tiles ────────────────────────────────────────────────
    {
        "id": "static_tile",
        "name": "Static Tile",
        "desc": "Zaps the piece with a jolt, randomising its next move direction.",
        "rarity": "common",
        "phase": 1,
        "weight": 0.9,
        "cooldown": 0,
        "tags": ["chaos", "movement"],
        "effects": [{"type": "chaos", "player": "self", "amount": 1}],
        "meta": {"duration": 5, "visual": (255, 255, 80)},
    },
    {
        "id": "lightning_conduit",
        "name": "Lightning Conduit",
        "desc": "Chains lightning to all pieces within two squares, dealing damage to each.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.35,
        "cooldown": 0,
        "tags": ["damage", "chaos"],
        "effects": [
            {"type": "chaos", "player": "self", "amount": 3},
            {"type": "chaos", "player": "opponent", "amount": 2},
        ],
        "meta": {"duration": 3, "visual": (240, 240, 50)},
    },
    # ── Poison Mist ────────────────────────────────────────────────
    {
        "id": "toxic_fog",
        "name": "Toxic Fog",
        "desc": "Applies a poison counter — the piece is destroyed after 4 turns if not cleansed.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 0,
        "tags": ["damage", "trap"],
        "effects": [{"type": "chaos", "player": "self", "amount": 2}],
        "meta": {"duration": 4, "visual": (80, 180, 60)},
    },
    {
        "id": "miasma_cloud",
        "name": "Miasma Cloud",
        "desc": "A thick poisonous cloud that weakens every piece in a 3x3 area each turn.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.1,
        "cooldown": 0,
        "tags": ["damage", "terrain", "chaos"],
        "effects": [
            {"type": "chaos", "player": "self", "amount": 4},
            {"type": "chaos", "player": "opponent", "amount": 3},
        ],
        "meta": {"duration": 5, "visual": (60, 140, 40)},
    },
]
