ITEMS = [
    # =========================================================================
    # PHASE 1-2: BASIC ITEMS (10) — cost 2-6
    # =========================================================================
    {
        "id": "wooden_shield",
        "name": "Wooden Shield",
        "desc": "A simple wooden shield that absorbs the next hit on the equipped piece.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 0,
        "tags": ["damage"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 0},
        ],
        "meta": {"cost": 3, "item_type": "equipment"},
    },
    {
        "id": "rusty_dagger",
        "name": "Rusty Dagger",
        "desc": "A dull but serviceable dagger that destroys a random enemy pawn.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 2,
        "tags": ["damage", "destruction"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 0},
        ],
        "meta": {"cost": 4, "item_type": "weapon"},
    },
    {
        "id": "healing_salve",
        "name": "Healing Salve",
        "desc": "A soothing salve that grants a small gold bonus when applied.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.5,
        "cooldown": 1,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 3},
        ],
        "meta": {"cost": 2, "item_type": "consumable"},
    },
    {
        "id": "smoke_bomb",
        "name": "Smoke Bomb",
        "desc": "Creates a cloud of smoke that places a fog hazard on the board.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 3,
        "tags": ["hazard", "environmental"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "fog", "duration": 2},
        ],
        "meta": {"cost": 3, "item_type": "consumable"},
    },
    {
        "id": "lucky_charm",
        "name": "Lucky Charm",
        "desc": "A rabbit's foot pendant that increases gold gains for the owner.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.0,
        "cooldown": 0,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 4},
        ],
        "meta": {"cost": 4, "item_type": "equipment"},
    },
    {
        "id": "boots_of_haste",
        "name": "Boots of Haste",
        "desc": "Enchanted boots that teleport the equipped piece to a new position.",
        "rarity": "common",
        "phase": 1,
        "weight": 2.5,
        "cooldown": 3,
        "tags": ["movement", "teleport"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {"cost": 5, "item_type": "equipment"},
    },
    {
        "id": "pawn_ration",
        "name": "Pawn Ration",
        "desc": "Field rations that let you recruit a new pawn to an empty square.",
        "rarity": "common",
        "phase": 2,
        "weight": 2.5,
        "cooldown": 4,
        "tags": ["chaos"],
        "effects": [
            {"type": "spawn", "piece": "p", "square": "random_empty"},
        ],
        "meta": {"cost": 5, "item_type": "consumable"},
    },
    {
        "id": "ice_shard",
        "name": "Ice Shard",
        "desc": "A jagged shard of enchanted ice that freezes a random enemy piece.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["hazard"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 2},
        ],
        "meta": {"cost": 5, "item_type": "weapon"},
    },
    {
        "id": "coin_purse",
        "name": "Coin Purse",
        "desc": "A heavy purse filled with gold coins for immediate spending.",
        "rarity": "common",
        "phase": 1,
        "weight": 3.5,
        "cooldown": 0,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 6},
        ],
        "meta": {"cost": 6, "item_type": "consumable"},
    },
    {
        "id": "scouts_compass",
        "name": "Scout's Compass",
        "desc": "A compass that reveals and teleports a random enemy to an exposed position.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["movement", "teleport"],
        "effects": [
            {"type": "teleport", "target": "random_enemy"},
        ],
        "meta": {"cost": 6, "item_type": "utility"},
    },

    # =========================================================================
    # PHASE 2-3: INTERMEDIATE ITEMS (15) — cost 5-12
    # =========================================================================
    {
        "id": "fire_sword",
        "name": "Fire Sword",
        "desc": "A blazing sword that incinerates an enemy piece and leaves fire behind.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["damage", "destruction", "hazard"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 1},
            {"type": "place_hazard", "hazard_id": "fire", "duration": 2},
        ],
        "meta": {"cost": 8, "item_type": "weapon"},
    },
    {
        "id": "gold_magnet",
        "name": "Gold Magnet",
        "desc": "A magical lodestone that attracts gold from across the battlefield.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 8},
        ],
        "meta": {"cost": 7, "item_type": "utility"},
    },
    {
        "id": "chaos_orb",
        "name": "Chaos Orb",
        "desc": "A swirling orb of raw chaos energy that disrupts both players equally.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["chaos"],
        "effects": [
            {"type": "chaos", "player": "both", "amount": 4},
        ],
        "meta": {"cost": 6, "item_type": "consumable"},
    },
    {
        "id": "teleport_scroll",
        "name": "Teleport Scroll",
        "desc": "An ancient scroll that teleports a random piece to a new square.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 2.0,
        "cooldown": 3,
        "tags": ["teleport", "movement"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {"cost": 5, "item_type": "consumable"},
    },
    {
        "id": "knights_lance",
        "name": "Knight's Lance",
        "desc": "A sturdy lance that transforms a pawn into a gallant knight.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.5,
        "cooldown": 5,
        "tags": ["transform"],
        "effects": [
            {"type": "transform", "target": "random_any", "into": "n"},
        ],
        "meta": {"cost": 8, "item_type": "equipment"},
    },
    {
        "id": "frost_grenade",
        "name": "Frost Grenade",
        "desc": "An explosive frost device that freezes an enemy piece and creates ice.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["hazard", "damage"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 2},
            {"type": "place_hazard", "hazard_id": "ice", "duration": 3},
        ],
        "meta": {"cost": 9, "item_type": "weapon"},
    },
    {
        "id": "mercenary_contract",
        "name": "Mercenary Contract",
        "desc": "Hire a sellsword knight to join your forces on an empty square.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 5,
        "tags": ["chaos"],
        "effects": [
            {"type": "spawn", "piece": "n", "square": "random_empty"},
        ],
        "meta": {"cost": 10, "item_type": "consumable"},
    },
    {
        "id": "swap_stone",
        "name": "Swap Stone",
        "desc": "A mystical stone that switches two random pieces' positions on the board.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "swap", "target": "random_any"},
        ],
        "meta": {"cost": 6, "item_type": "utility"},
    },
    {
        "id": "lava_flask",
        "name": "Lava Flask",
        "desc": "A sealed flask of molten rock that creates a lava hazard when smashed.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["hazard", "destruction"],
        "effects": [
            {"type": "place_hazard", "hazard_id": "lava", "duration": 3},
            {"type": "destroy", "target": "random_any", "radius": 1},
        ],
        "meta": {"cost": 9, "item_type": "consumable"},
    },
    {
        "id": "thieves_gloves",
        "name": "Thieves' Gloves",
        "desc": "Enchanted gloves that steal gold directly from your opponent's coffers.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "opponent", "amount": -6},
            {"type": "gold", "player": "self", "amount": 4},
        ],
        "meta": {"cost": 10, "item_type": "equipment"},
    },
    {
        "id": "mirror_shard",
        "name": "Mirror Shard",
        "desc": "A fragment of a magic mirror that swaps a piece with its reflected counterpart.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.2,
        "cooldown": 5,
        "tags": ["movement", "chaos"],
        "effects": [
            {"type": "swap", "target": "random_any"},
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {"cost": 11, "item_type": "utility"},
    },
    {
        "id": "explosive_barrel",
        "name": "Explosive Barrel",
        "desc": "A volatile barrel that detonates on use, destroying nearby pieces.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 4,
        "tags": ["damage", "destruction"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
        ],
        "meta": {"cost": 10, "item_type": "consumable"},
    },
    {
        "id": "shadow_cloak",
        "name": "Shadow Cloak",
        "desc": "A cloak woven from shadows that teleports the wearer to safety.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 1.8,
        "cooldown": 4,
        "tags": ["movement", "teleport"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
        ],
        "meta": {"cost": 7, "item_type": "equipment"},
    },
    {
        "id": "war_drum",
        "name": "War Drum",
        "desc": "Beating the drum inspires your troops, spawning a pawn and granting gold.",
        "rarity": "uncommon",
        "phase": 3,
        "weight": 1.5,
        "cooldown": 5,
        "tags": ["economy", "chaos"],
        "effects": [
            {"type": "spawn", "piece": "p", "square": "random_empty"},
            {"type": "gold", "player": "self", "amount": 3},
        ],
        "meta": {"cost": 8, "item_type": "utility"},
    },
    {
        "id": "cursed_amulet",
        "name": "Cursed Amulet",
        "desc": "A dark amulet that damages a random enemy but curses the ground beneath.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.2,
        "cooldown": 5,
        "tags": ["damage", "hazard"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 0},
            {"type": "place_hazard", "hazard_id": "curse", "duration": 3},
        ],
        "meta": {"cost": 12, "item_type": "equipment"},
    },

    # =========================================================================
    # PHASE 3-4: ADVANCED ITEMS (10) — cost 10-18
    # =========================================================================
    {
        "id": "dragonfire_staff",
        "name": "Dragonfire Staff",
        "desc": "A staff imbued with dragon flame that incinerates enemies in a wide radius.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 6,
        "tags": ["damage", "destruction"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 2},
            {"type": "place_hazard", "hazard_id": "fire", "duration": 3},
        ],
        "meta": {"cost": 14, "item_type": "weapon"},
    },
    {
        "id": "queens_crown",
        "name": "Queen's Crown",
        "desc": "A magnificent crown that transforms any piece into a powerful queen.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.8,
        "cooldown": 7,
        "tags": ["transform"],
        "effects": [
            {"type": "transform", "target": "random_any", "into": "q"},
        ],
        "meta": {"cost": 15, "item_type": "equipment"},
    },
    {
        "id": "wormhole_device",
        "name": "Wormhole Device",
        "desc": "An arcane contraption that rips open wormholes, teleporting multiple pieces.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["teleport", "chaos"],
        "effects": [
            {"type": "teleport", "target": "random_any"},
            {"type": "teleport", "target": "random_enemy"},
        ],
        "meta": {"cost": 12, "item_type": "utility"},
    },
    {
        "id": "necromancers_tome",
        "name": "Necromancer's Tome",
        "desc": "A forbidden book that raises two fallen pawns from the dead.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["chaos"],
        "effects": [
            {"type": "spawn", "piece": "p", "square": "random_empty"},
            {"type": "spawn", "piece": "p", "square": "random_empty"},
        ],
        "meta": {"cost": 13, "item_type": "utility"},
    },
    {
        "id": "avalanche_horn",
        "name": "Avalanche Horn",
        "desc": "A massive horn whose blast triggers an avalanche of ice and destruction.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["destruction", "hazard", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "place_hazard", "hazard_id": "ice", "duration": 3},
        ],
        "meta": {"cost": 14, "item_type": "weapon"},
    },
    {
        "id": "gold_mine_deed",
        "name": "Gold Mine Deed",
        "desc": "A deed granting ownership of a gold mine, producing a massive payout.",
        "rarity": "rare",
        "phase": 3,
        "weight": 1.0,
        "cooldown": 5,
        "tags": ["economy"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 15},
        ],
        "meta": {"cost": 12, "item_type": "utility"},
    },
    {
        "id": "plague_vial",
        "name": "Plague Vial",
        "desc": "A vial of concentrated plague that freezes and poisons the board.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["hazard", "damage"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "place_hazard", "hazard_id": "plague", "duration": 3},
        ],
        "meta": {"cost": 15, "item_type": "weapon"},
    },
    {
        "id": "dimensional_anchor",
        "name": "Dimensional Anchor",
        "desc": "An anchor that stabilizes a rift, swapping and teleporting enemy pieces.",
        "rarity": "rare",
        "phase": 4,
        "weight": 0.8,
        "cooldown": 6,
        "tags": ["teleport", "chaos", "board"],
        "effects": [
            {"type": "swap", "target": "random_any"},
            {"type": "teleport", "target": "random_enemy"},
        ],
        "meta": {"cost": 16, "item_type": "utility"},
    },
    {
        "id": "siege_engine",
        "name": "Siege Engine",
        "desc": "A devastating war machine that smashes through enemy lines with brutal force.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 7,
        "tags": ["damage", "destruction"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 2},
            {"type": "destroy", "target": "random_enemy", "radius": 1},
        ],
        "meta": {"cost": 18, "item_type": "weapon"},
    },
    {
        "id": "time_crystal",
        "name": "Time Crystal",
        "desc": "A crystallized fragment of time that freezes multiple enemy pieces at once.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.6,
        "cooldown": 7,
        "tags": ["chaos"],
        "effects": [
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "freeze", "target": "random_any", "duration": 2},
        ],
        "meta": {"cost": 16, "item_type": "utility"},
    },

    # =========================================================================
    # PHASE 4-5: LEGENDARY ITEMS (5) — cost 15-25
    # =========================================================================
    {
        "id": "excalibur",
        "name": "Excalibur",
        "desc": "The legendary sword of kings that obliterates enemies and transforms the wielder.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["damage", "destruction", "transform"],
        "effects": [
            {"type": "destroy", "target": "random_enemy", "radius": 2},
            {"type": "transform", "target": "random_any", "into": "q"},
        ],
        "meta": {"cost": 25, "item_type": "weapon"},
    },
    {
        "id": "philosophers_stone",
        "name": "Philosopher's Stone",
        "desc": "The mythical stone that transmutes everything it touches into gold.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["economy", "transform"],
        "effects": [
            {"type": "gold", "player": "self", "amount": 20},
            {"type": "transform", "target": "random_any", "into": "q"},
        ],
        "meta": {"cost": 22, "item_type": "utility"},
    },
    {
        "id": "pandoras_box",
        "name": "Pandora's Box",
        "desc": "Opening this cursed box unleashes total chaos on both players and the board.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["chaos", "destruction", "hazard"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 3},
            {"type": "chaos", "player": "both", "amount": 8},
            {"type": "place_hazard", "hazard_id": "curse", "duration": 4},
        ],
        "meta": {"cost": 20, "item_type": "consumable"},
    },
    {
        "id": "ark_of_storms",
        "name": "Ark of Storms",
        "desc": "An ancient ark crackling with lightning that devastates the entire battlefield.",
        "rarity": "legendary",
        "phase": 4,
        "weight": 0.3,
        "cooldown": 10,
        "tags": ["damage", "destruction", "environmental"],
        "effects": [
            {"type": "destroy", "target": "random_any", "radius": 2},
            {"type": "destroy", "target": "random_enemy", "radius": 1},
            {"type": "place_hazard", "hazard_id": "lightning", "duration": 3},
        ],
        "meta": {"cost": 18, "item_type": "weapon"},
    },
    {
        "id": "orb_of_dominion",
        "name": "Orb of Dominion",
        "desc": "A world-shaping orb that spawns knights, freezes foes, and warps reality itself.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.2,
        "cooldown": 12,
        "tags": ["chaos", "teleport", "transform"],
        "effects": [
            {"type": "spawn", "piece": "n", "square": "random_empty"},
            {"type": "spawn", "piece": "n", "square": "random_empty"},
            {"type": "freeze", "target": "random_any", "duration": 3},
            {"type": "teleport", "target": "random_enemy"},
        ],
        "meta": {"cost": 15, "item_type": "utility"},
    },
]
