MINIGAMES = [
    # ── Reaction (5) ─────────────────────────────────────────────
    {
        "id": "bullet_dodge",
        "name": "Bullet Dodge",
        "desc": "Tap the correct side to dodge incoming projectiles before they hit your king.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 3,
        "tags": ["reaction"],
        "effects": [],
        "meta": {
            "type": "reaction",
            "difficulty": 1,
            "time_limit": 5.0,
            "success_effects": [{"type": "shield", "target": "random_self", "duration": 2}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 5}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": -1}],
        },
    },
    {
        "id": "fork_reflex",
        "name": "Fork Reflex",
        "desc": "Spot which piece is being forked and click it before time runs out.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.8,
        "cooldown": 4,
        "tags": ["reaction"],
        "effects": [],
        "meta": {
            "type": "reaction",
            "difficulty": 3,
            "time_limit": 4.0,
            "success_effects": [{"type": "destroy", "target": "random_enemy"}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 10}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 2}],
        },
    },
    {
        "id": "blitz_tap",
        "name": "Blitz Tap",
        "desc": "Tap the flashing square as many times as possible in three seconds.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 3,
        "tags": ["reaction"],
        "effects": [],
        "meta": {
            "type": "reaction",
            "difficulty": 2,
            "time_limit": 3.0,
            "success_effects": [{"type": "extra_turn"}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 8}],
            "fail_effects": [],
        },
    },
    {
        "id": "arrow_storm",
        "name": "Arrow Storm",
        "desc": "Swipe in the direction of each arrow before it fades — survive the volley.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.5,
        "cooldown": 5,
        "tags": ["reaction"],
        "effects": [],
        "meta": {
            "type": "reflex",
            "difficulty": 4,
            "time_limit": 6.0,
            "success_effects": [
                {"type": "destroy", "target": "random_enemy"},
                {"type": "gold", "player": "self", "amount": 15},
            ],
            "partial_effects": [{"type": "shield", "target": "random_self", "duration": 1}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 3}],
        },
    },
    {
        "id": "kings_parry",
        "name": "King's Parry",
        "desc": "Press the parry button at the exact frame the sword strikes your king.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.3,
        "cooldown": 6,
        "tags": ["reaction"],
        "effects": [],
        "meta": {
            "type": "reflex",
            "difficulty": 5,
            "time_limit": 3.5,
            "success_effects": [
                {"type": "destroy", "target": "random_enemy"},
                {"type": "shield", "target": "random_self", "duration": 3},
            ],
            "partial_effects": [{"type": "shield", "target": "random_self", "duration": 1}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 4}],
        },
    },
    # ── Memory (4) ────────────────────────────────────────────────
    {
        "id": "piece_recall",
        "name": "Piece Recall",
        "desc": "The board flashes briefly — name every piece that was on the third rank.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 4,
        "tags": ["memory"],
        "effects": [],
        "meta": {
            "type": "memory",
            "difficulty": 2,
            "time_limit": 8.0,
            "success_effects": [{"type": "draw_cards", "count": 2}],
            "partial_effects": [{"type": "draw_cards", "count": 1}],
            "fail_effects": [],
        },
    },
    {
        "id": "ghost_squares",
        "name": "Ghost Squares",
        "desc": "Remember which squares glowed and select them all from memory.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.7,
        "cooldown": 5,
        "tags": ["memory"],
        "effects": [],
        "meta": {
            "type": "memory",
            "difficulty": 3,
            "time_limit": 10.0,
            "success_effects": [{"type": "spawn", "piece": "n", "square": "random_empty"}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 10}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 1}],
        },
    },
    {
        "id": "deja_vu",
        "name": "Déjà Vu",
        "desc": "Watch a sequence of moves replayed, then identify the one move that changed.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.5,
        "cooldown": 6,
        "tags": ["memory"],
        "effects": [],
        "meta": {
            "type": "memory",
            "difficulty": 4,
            "time_limit": 12.0,
            "success_effects": [
                {"type": "gold", "player": "self", "amount": 20},
                {"type": "draw_cards", "count": 2},
            ],
            "partial_effects": [{"type": "draw_cards", "count": 1}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 2}],
        },
    },
    {
        "id": "mind_palace",
        "name": "Mind Palace",
        "desc": "Memorise a full board state, then reconstruct it after it vanishes.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.15,
        "cooldown": 8,
        "tags": ["memory"],
        "effects": [],
        "meta": {
            "type": "memory",
            "difficulty": 5,
            "time_limit": 15.0,
            "success_effects": [
                {"type": "spawn", "piece": "q", "square": "random_empty"},
                {"type": "gold", "player": "self", "amount": 30},
            ],
            "partial_effects": [{"type": "draw_cards", "count": 2}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 3}],
        },
    },
    # ── Trivia (3) ────────────────────────────────────────────────
    {
        "id": "chess_lore",
        "name": "Chess Lore",
        "desc": "Answer a trivia question about real-world chess history or famous games.",
        "rarity": "common",
        "phase": 1,
        "weight": 0.9,
        "cooldown": 4,
        "tags": ["trivia"],
        "effects": [],
        "meta": {
            "type": "trivia",
            "difficulty": 2,
            "time_limit": 10.0,
            "success_effects": [{"type": "gold", "player": "self", "amount": 15}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 5}],
            "fail_effects": [],
        },
    },
    {
        "id": "grandmaster_gambit",
        "name": "Grandmaster Gambit",
        "desc": "Identify the correct next move from a famous grandmaster game.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 6,
        "tags": ["trivia"],
        "effects": [],
        "meta": {
            "type": "trivia",
            "difficulty": 4,
            "time_limit": 12.0,
            "success_effects": [
                {"type": "extra_turn"},
                {"type": "gold", "player": "self", "amount": 20},
            ],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 10}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 2}],
        },
    },
    {
        "id": "name_the_opening",
        "name": "Name the Opening",
        "desc": "Watch three moves play out and name the chess opening before the clock expires.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.7,
        "cooldown": 5,
        "tags": ["trivia"],
        "effects": [],
        "meta": {
            "type": "trivia",
            "difficulty": 3,
            "time_limit": 8.0,
            "success_effects": [{"type": "draw_cards", "count": 2}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 8}],
            "fail_effects": [],
        },
    },
    # ── Typing (3) ────────────────────────────────────────────────
    {
        "id": "notation_sprint",
        "name": "Notation Sprint",
        "desc": "Type a sequence of algebraic notation moves as fast as you can.",
        "rarity": "common",
        "phase": 1,
        "weight": 0.9,
        "cooldown": 3,
        "tags": ["typing"],
        "effects": [],
        "meta": {
            "type": "typing",
            "difficulty": 2,
            "time_limit": 8.0,
            "success_effects": [{"type": "gold", "player": "self", "amount": 12}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 4}],
            "fail_effects": [],
        },
    },
    {
        "id": "spell_incantation",
        "name": "Spell Incantation",
        "desc": "Type the magic incantation perfectly to unleash a devastating board spell.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.3,
        "cooldown": 7,
        "tags": ["typing"],
        "effects": [],
        "meta": {
            "type": "typing",
            "difficulty": 4,
            "time_limit": 6.0,
            "success_effects": [
                {"type": "destroy", "target": "random_enemy"},
                {"type": "spawn", "piece": "n", "square": "random_empty"},
            ],
            "partial_effects": [{"type": "chaos", "player": "opponent", "amount": 2}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 3}],
        },
    },
    {
        "id": "typo_defusal",
        "name": "Typo Defusal",
        "desc": "Spot and retype the incorrectly notated move before the bomb explodes.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.7,
        "cooldown": 4,
        "tags": ["typing"],
        "effects": [],
        "meta": {
            "type": "typing",
            "difficulty": 3,
            "time_limit": 7.0,
            "success_effects": [{"type": "shield", "target": "random_self", "duration": 2}],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 6}],
            "fail_effects": [{"type": "destroy", "target": "random_enemy"}],
        },
    },
    # ── Sequence (2) ──────────────────────────────────────────────
    {
        "id": "ritual_dance",
        "name": "Ritual Dance",
        "desc": "Repeat an increasingly long sequence of directional inputs without mistakes.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 5,
        "tags": ["memory", "reaction"],
        "effects": [],
        "meta": {
            "type": "sequence",
            "difficulty": 3,
            "time_limit": 10.0,
            "success_effects": [
                {"type": "extra_turn"},
                {"type": "gold", "player": "self", "amount": 10},
            ],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 5}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 1}],
        },
    },
    {
        "id": "checkmate_combo",
        "name": "Checkmate Combo",
        "desc": "Execute a precise sequence of captures in the correct order to score a combo.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.25,
        "cooldown": 7,
        "tags": ["puzzle", "reaction"],
        "effects": [],
        "meta": {
            "type": "sequence",
            "difficulty": 5,
            "time_limit": 12.0,
            "success_effects": [
                {"type": "destroy", "target": "random_enemy"},
                {"type": "destroy", "target": "random_enemy"},
                {"type": "gold", "player": "self", "amount": 25},
            ],
            "partial_effects": [{"type": "destroy", "target": "random_enemy"}],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 4}],
        },
    },
    # ── Luck (3) ──────────────────────────────────────────────────
    {
        "id": "coin_of_fate",
        "name": "Coin of Fate",
        "desc": "Flip a cosmic coin — heads you gain a piece, tails your opponent does.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 3,
        "tags": ["luck"],
        "effects": [],
        "meta": {
            "type": "luck",
            "difficulty": 1,
            "time_limit": 5.0,
            "success_effects": [{"type": "spawn", "piece": "n", "square": "random_empty"}],
            "partial_effects": [],
            "fail_effects": [{"type": "chaos", "player": "opponent", "amount": 2}],
        },
    },
    {
        "id": "chaos_roulette",
        "name": "Chaos Roulette",
        "desc": "Spin the wheel of chaos — anything from treasure to total board wipe.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 6,
        "tags": ["luck"],
        "effects": [],
        "meta": {
            "type": "luck",
            "difficulty": 3,
            "time_limit": 5.0,
            "success_effects": [
                {"type": "spawn", "piece": "q", "square": "random_empty"},
                {"type": "gold", "player": "self", "amount": 25},
            ],
            "partial_effects": [{"type": "draw_cards", "count": 1}],
            "fail_effects": [
                {"type": "destroy", "target": "random_enemy"},
                {"type": "chaos", "player": "opponent", "amount": 5},
            ],
        },
    },
    {
        "id": "pandoras_pawn",
        "name": "Pandora's Pawn",
        "desc": "Open the cursed box — incredible reward or spectacular disaster, no in-between.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.1,
        "cooldown": 8,
        "tags": ["luck"],
        "effects": [],
        "meta": {
            "type": "luck",
            "difficulty": 5,
            "time_limit": 4.0,
            "success_effects": [
                {"type": "spawn", "piece": "q", "square": "random_empty"},
                {"type": "extra_turn"},
                {"type": "gold", "player": "self", "amount": 50},
            ],
            "partial_effects": [{"type": "gold", "player": "self", "amount": 15}],
            "fail_effects": [
                {"type": "destroy", "target": "random_enemy"},
                {"type": "destroy", "target": "random_enemy"},
                {"type": "chaos", "player": "opponent", "amount": 8},
            ],
        },
    },
]
