MUTATIONS = [
    # ── Shield ─────────────────────────────────────────────────────
    {
        "id": "iron_carapace",
        "name": "Iron Carapace",
        "desc": "Wraps the piece in enchanted iron, blocking the next capture attempt against it.",
        "rarity": "common",
        "phase": 1,
        "weight": 1.0,
        "cooldown": 0,
        "tags": ["defense", "buff"],
        "effects": [],
        "meta": {"duration": 3, "mutation_type": "shield"},
    },
    {
        "id": "aegis_ward",
        "name": "Aegis Ward",
        "desc": "Projects a divine barrier that absorbs two capture attempts before shattering.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 0,
        "tags": ["defense", "buff"],
        "effects": [],
        "meta": {"duration": 5, "mutation_type": "shield"},
    },
    # ── Freeze ─────────────────────────────────────────────────────
    {
        "id": "permafrost_bind",
        "name": "Permafrost Bind",
        "desc": "Encases the piece in ice — it cannot move or be moved for several turns.",
        "rarity": "common",
        "phase": 1,
        "weight": 0.9,
        "cooldown": 0,
        "tags": ["debuff", "movement"],
        "effects": [],
        "meta": {"duration": 3, "mutation_type": "freeze"},
    },
    {
        "id": "absolute_zero",
        "name": "Absolute Zero",
        "desc": "Deep-freezes the piece and all adjacent allies, locking an entire formation.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.25,
        "cooldown": 0,
        "tags": ["debuff", "movement", "chaos"],
        "effects": [],
        "meta": {"duration": 4, "mutation_type": "freeze"},
    },
    # ── Haste ──────────────────────────────────────────────────────
    {
        "id": "adrenaline_surge",
        "name": "Adrenaline Surge",
        "desc": "The piece moves with frantic energy, gaining a second move action each turn.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 0,
        "tags": ["buff", "movement"],
        "effects": [],
        "meta": {"duration": 4, "mutation_type": "haste"},
    },
    {
        "id": "time_warp",
        "name": "Time Warp",
        "desc": "Bends time around the piece so it acts twice before the opponent can respond.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.2,
        "cooldown": 0,
        "tags": ["buff", "movement", "chaos"],
        "effects": [],
        "meta": {"duration": 3, "mutation_type": "haste"},
    },
    # ── Enrage ─────────────────────────────────────────────────────
    {
        "id": "berserker_fury",
        "name": "Berserker Fury",
        "desc": "The piece enters a blind rage, extending its capture range by one square in every direction.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.6,
        "cooldown": 0,
        "tags": ["buff", "combat"],
        "effects": [],
        "meta": {"duration": 4, "mutation_type": "enrage"},
    },
    {
        "id": "blood_frenzy",
        "name": "Blood Frenzy",
        "desc": "Each successful capture extends the rage duration and further expands capture range.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 0,
        "tags": ["buff", "combat", "chaos"],
        "effects": [],
        "meta": {"duration": 5, "mutation_type": "enrage"},
    },
    # ── Poison ─────────────────────────────────────────────────────
    {
        "id": "creeping_rot",
        "name": "Creeping Rot",
        "desc": "A slow-acting venom that destroys the piece after a set number of turns.",
        "rarity": "common",
        "phase": 1,
        "weight": 0.9,
        "cooldown": 0,
        "tags": ["debuff", "combat"],
        "effects": [],
        "meta": {"duration": 5, "mutation_type": "poison"},
    },
    {
        "id": "pandemic_spore",
        "name": "Pandemic Spore",
        "desc": "The poison spreads to any piece the infected one touches, creating a chain of decay.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.2,
        "cooldown": 0,
        "tags": ["debuff", "combat", "chaos"],
        "effects": [],
        "meta": {"duration": 6, "mutation_type": "poison"},
    },
    # ── Ghost ──────────────────────────────────────────────────────
    {
        "id": "spectral_phase",
        "name": "Spectral Phase",
        "desc": "The piece becomes ethereal, passing through other pieces as if they weren't there.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.5,
        "cooldown": 0,
        "tags": ["buff", "movement"],
        "effects": [],
        "meta": {"duration": 4, "mutation_type": "ghost"},
    },
    {
        "id": "wraith_walk",
        "name": "Wraith Walk",
        "desc": "The piece can move through occupied squares and cannot be captured while in motion.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.35,
        "cooldown": 0,
        "tags": ["buff", "movement", "defense"],
        "effects": [],
        "meta": {"duration": 3, "mutation_type": "ghost"},
    },
    # ── Magnet ─────────────────────────────────────────────────────
    {
        "id": "lodestone_pulse",
        "name": "Lodestone Pulse",
        "desc": "Generates a magnetic field that pulls nearby enemy pieces one square closer each turn.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.4,
        "cooldown": 0,
        "tags": ["chaos", "movement"],
        "effects": [],
        "meta": {"duration": 4, "mutation_type": "magnet"},
    },
    # ── Mirror ─────────────────────────────────────────────────────
    {
        "id": "reflection_matrix",
        "name": "Reflection Matrix",
        "desc": "When an enemy attempts to capture this piece, the attacker is captured instead.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.2,
        "cooldown": 0,
        "tags": ["defense", "combat"],
        "effects": [],
        "meta": {"duration": 3, "mutation_type": "mirror"},
    },
    # ── Volatile ───────────────────────────────────────────────────
    {
        "id": "unstable_core",
        "name": "Unstable Core",
        "desc": "When captured, the piece detonates and destroys all pieces on adjacent squares.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.55,
        "cooldown": 0,
        "tags": ["combat", "chaos"],
        "effects": [],
        "meta": {"duration": -1, "mutation_type": "volatile"},
    },
    {
        "id": "nuclear_payload",
        "name": "Nuclear Payload",
        "desc": "Massive explosion on capture — destroys everything in a two-square radius.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.1,
        "cooldown": 0,
        "tags": ["combat", "chaos"],
        "effects": [],
        "meta": {"duration": -1, "mutation_type": "volatile"},
    },
    # ── Royal ──────────────────────────────────────────────────────
    {
        "id": "crown_ascendant",
        "name": "Crown Ascendant",
        "desc": "A pawn believes it is royalty, gaining the movement abilities of a queen.",
        "rarity": "legendary",
        "phase": 5,
        "weight": 0.1,
        "cooldown": 0,
        "tags": ["transform", "buff"],
        "effects": [],
        "meta": {"duration": 4, "mutation_type": "royal"},
    },
    # ── Gravity ────────────────────────────────────────────────────
    {
        "id": "gravity_anchor",
        "name": "Gravity Anchor",
        "desc": "The piece becomes so heavy it cannot be displaced by any hazard or card effect.",
        "rarity": "uncommon",
        "phase": 2,
        "weight": 0.55,
        "cooldown": 0,
        "tags": ["defense", "movement"],
        "effects": [],
        "meta": {"duration": 5, "mutation_type": "gravity"},
    },
    # ── Vampiric ───────────────────────────────────────────────────
    {
        "id": "vampiric_bite",
        "name": "Vampiric Bite",
        "desc": "Each successful capture heals the piece and extends its lifespan by two turns.",
        "rarity": "rare",
        "phase": 3,
        "weight": 0.35,
        "cooldown": 0,
        "tags": ["buff", "combat"],
        "effects": [],
        "meta": {"duration": 6, "mutation_type": "vampiric"},
    },
    # ── Berserker ─────────────────────────────────────────────────
    {
        "id": "berserker_rage",
        "name": "Berserker Rage",
        "desc": "The piece attacks in all directions but can no longer retreat backwards.",
        "rarity": "epic",
        "phase": 4,
        "weight": 0.30,
        "cooldown": 0,
        "tags": ["buff", "combat", "chaos"],
        "effects": [],
        "meta": {"duration": 3, "mutation_type": "berserker"},
    },
]
